package com.lenovo.ai.admin.generator.mapper;

import com.lenovo.ai.admin.generator.model.USER;

public interface USERMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Aug 18 16:01:09 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Aug 18 16:01:09 CST 2017
     */
    int insert(USER record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Aug 18 16:01:09 CST 2017
     */
    int insertSelective(USER record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Aug 18 16:01:09 CST 2017
     */
    USER selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Aug 18 16:01:09 CST 2017
     */
    int updateByPrimaryKeySelective(USER record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Aug 18 16:01:09 CST 2017
     */
    int updateByPrimaryKey(USER record);
}